# Generated by Django 3.2.7 on 2021-09-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wica_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('book', 'BOOK'), ('men_fashion', 'MEN FASHION'), ('women_fashion', 'WOMEN FASHION')], max_length=100, null=True),
        ),
    ]
